Auto setup script (#1)
* automated setup & port detection script

* Fix bad substitution

* don't page journal

* suppress exit code and do a one shot

diff --git a/8bitdo-sleep-fix b/8bitdo-sleep-fix
--- a/8bitdo-sleep-fix
+++ b/8bitdo-sleep-fix
@@ -7,22 +7,12 @@ trap 'exit 0' EXIT TERM INT
 # Set the port to the one your controller is connected to.
 # You can find this by running:
 #    sudo dmesg | grep -i 8bit
-PORT="1-6"
+CONFIG_FILE="${_8BITDO_SLEEP_FIX_CONFIG_FILE:-/etc/default/8bitdo-sleep-fix}"
 
-HUB="usb1"
-
-# Set the vendor and product ID for your controller.
-# You can find this by running:
-#    lsusb
-# make sure the controller is on when you do this so you get
-# the correct product IDs.
-# Run lsusb before and after you put the controller to sleep to get the correct IDs.
-# IDLE_PRODUCT_ID is the product ID of the controller when it is turned off.
-# We watch for this to know when the controller has been turned off and it is safe to enable wakeup
-# at the hub level. If you don't set this correctly, the controller will wake up the system immediately after sleep.
-VENDOR_ID=2dc8
-PRODUCT_ID=3106
-IDLE_PRODUCT_ID=3109
+if [ -z "$PORT" ] || [ -z "$HUB" ] || [ -z "$VENDOR_ID" ] || [ -z "$PRODUCT_ID" ] || [ -z "$IDLE_PRODUCT_ID" ]; then
+    echo "Missing 8BitDo configuration. Set PORT, HUB, VENDOR_ID, PRODUCT_ID, and IDLE_PRODUCT_ID in $CONFIG_FILE" >&2
+    exit 1
+fi
 
 case $1 in
     sleep)
